### ISSUE TITLE
How to block .yabo-firstcol-box?

### ISSUE THREAD

**Issue by icedrain0611** [wolfcon/RIP-HLTV-BET#1]

**Comment by wolfcon** [comment]
This is only visual pollution. Real URL has been removed.
If you wanna block that background, you can do this in your ADP advanced rule.
```css
// add 1 rule
hltv.org##[class*="yabo"]
```

**Comment by wolfcon** [comment]
I will write some code to achieve similar function to those users who have not install ADP.

Check it out later. Maybe tomorrow🧐

**Comment by wolfcon** [comment]
Already added in `0.4` version. Just update and try it.

**Comment by icedrain0611** [comment]
谢谢，可以了
