### ISSUE TITLE
需要添加新的广告位置屏蔽

### ISSUE THREAD

**Issue by icedrain0611** [wolfcon/RIP-HLTV-BET#12]
目前版本v1.13
https://www.hltv.org/matches/2372330/g2-vs-vitality-iem-dallas-2024
图例
![image](https://github.com/wolfcon/RIP-HLTV-BET/assets/35239552/b18df510-8e4a-419f-b89a-dccae8851971)

**Comment by wolfcon** [comment]
我这里没有这个广告框...方便在你那边使用浏览器的保存页面, 保存一个完整页面传上来吗

**Comment by icedrain0611** [comment]
QAQ，现在我进去看，也是没有了
