### ISSUE TITLE
拦截的方法依然效率比较低

### ISSUE THREAD

**Issue by icedrain0611** [wolfcon/RIP-HLTV-BET#2]
现在拦截bet 广告已经可以完全屏蔽了！
    但是拦截广告的行为在油猴里却是等待网页全部加载完成之后再进行屏蔽，这意味着在网页完全加载前广告是能完全显示的！
并且进入每一个子页面都会仍旧加载广告-屏蔽广告。
    导致这个方法去屏蔽广告就像采访中问记着能不能给我脸上打马赛克那样，有用，但是没什么用

**Comment by wolfcon** [comment]
犹如描述那般: 只是简单粗暴的屏蔽罢了.
如果要屏蔽加载, 那你可有的忙了. 那些菠菜网站天天换地址, 而且无任何规律. 试问你要怎么办? 

我之前是使用 ADP 的, 但是自从菠菜网天天换地址, 花式换, 我来跟你说说我之前用 ADP 时的经历路程:
- 最初的屏蔽失效, 菠菜网换地址
- 筛选 class 标签, hltv 采用动态生成 ClassName 的方式, 屏蔽失效
- hltv 采用多层嵌套, 並且使用\<aside\>标签替代\<div\>标签.

**由于我非 js 前端开发人员, 所以屏蔽效果和屏蔽方法的选择上可能有些不尽人意, 欢迎您的 PR, 让 hltv 的广告消失于无形**

**Comment by wolfcon** [comment]
Just try version `1.0`

**Comment by icedrain0611** [comment]
看上去已经被完美阻止了，非常感谢！

**Comment by wolfcon** [comment]
如果您觉得还不错, 来颗🌟吧
