### ISSUE TITLE
1.1版本需要修一下

### ISSUE THREAD

**Issue by icedrain0611** [wolfcon/RIP-HLTV-BET#3]
1.1版本进入到任意hltv的新闻页面或者比赛页会遭遇无与伦比的性能问题~
1.0正常，回退后可以正常使用

**Comment by wolfcon** [comment]
emmm, 好像的确是有这个问题, 得考虑考虑其他方案了. 

你那边`1.0` 在比赛页面不会有部分广告吗?

**Comment by icedrain0611** [comment]
可能那部分被我用adp屏蔽掉了吧~至少1.0基本是好用的

**Comment by wolfcon** [comment]
好了. 试试 `1.2` 吧.
已经修改了屏蔽逻辑. 采用和 ADBP 类似的逻辑了

**Comment by icedrain0611** [comment]
好的，谢谢！
