### ISSUE TITLE
报告2个bug

### ISSUE THREAD

**Issue by zdm9981** [wolfcon/RIP-HLTV-BET#6]
1.脚本会错误屏蔽首次登陆下方弹出的cookie选项按钮 导致无法选择
2. 此页面会屏蔽twitch频道 https://www.hltv.org/news/33368/live-eu-rmr-qualifier-3-tournament-hits-round-of-256

**Comment by wolfcon** [comment]
cookie 那个建议你用 ADP 直接屏蔽, 没有卵用的东西
2这个问题我瞅瞅

**Comment by zdm9981** [comment]
插件会屏蔽论谈帖子里的网址
https://www.hltv.org/forums/threads/2642112/gla1ve-tweet-d

**Comment by wolfcon** [comment]
已经解决了. 更新一下[1.7](https://github.com/wolfcon/RIP-HLTV-BET/commit/730a720e6078da65b60468223bd950b0febf3c90)吧. 顺带更新了hltv新的广告方案~

**Comment by zdm9981** [comment]
比赛页面的博彩赔率又出来了 能只屏蔽右边的国产赔率嘛 一大坨太难看了

**Comment by wolfcon** [comment]
淡定, hltv 的人也在监控, 都会随时改源码...我来瞅瞅先, 试试 `1.8` 吧~

**Comment by zdm9981** [comment]
比赛页面的博彩赔率再次出现

**Comment by wolfcon** [comment]
我这边没有啊. 是哪个页面?

**Comment by zdm9981** [comment]
比赛详情页面 https://imgur.com/a/chqejgC

**Comment by zdm9981** [comment]
刷新几次好像又没了 可能是缓存问题
